### ISSUE TITLE
Use Map()

### ISSUE THREAD

**Issue by antimatter96** [antimatter96/battleships#5]

**Comment by DavidCabal** [comment]
Is there any specific part of the code base that this ticket is referencing? Or just converting all of the "for" and "for in" loops to use built in array methods? (from my quick glance it seemed that most of them would do just fine with forEach) Happy to knock this out for you once I have some clarity on it.

**Comment by antimatter96** [comment]
The code base has changed a lot since I raised this issue. I don't remember what this referred to 😆 

Thanks for looking into the project. Any change that you'd like to suggest?
